### ISSUE TITLE
isar-community not support github workflow

### ISSUE THREAD

**Issue by guchengxi1994** [isar-community/isar#101]
### Discussed in https://github.com/isar-community/isar/discussions/100

<div type='discussions-op-text'>

<sup>Originally posted by **guchengxi1994** August 16, 2024</sup>
![image](https://github.com/user-attachments/assets/6479aecc-6105-4fcb-8fd7-24494d0da833)

cannot get packages from https://pub.isar-community.dev/ when using github workflow to build apps</div>

**Comment by vicenterusso** [comment]
Can you try 3.1.8?

**Comment by guchengxi1994** [comment]
@vicenterusso  3.1.8 works , thanks for help!
