### ISSUE TITLE
Isar is still using an older js 0.6.4 version. Add js 0.7.1 support

### ISSUE THREAD

**Issue by alexfeller** [isar-community/isar#16]
**Is your feature request related to a problem? Please describe.**
Unable to upgrade flutter native splash package due to the following issue:

Because isar 3.1.3 depends on js ^0.6.4 and flutter_native_splash >=2.3.12 depends on js ^0.7.1, isar 3.1.3 is incompatible with flutter_native_splash >=2.3.12.

**Describe the solution you'd like**
Upgrade isar js package from 0.6.4 to the most recent version 0.7.1

**Describe alternatives you've considered**
Alternative solution would be a downgrade of the flutter_native_splash package. Though it is recommended to upgrade js package to 0.7.1 in isar to stay up to date.

**Version**
 - Platform: Android
 - Flutter version: [3.19.2]
 - Isar version: [3.1.3]

**Comment by vicenterusso** [comment]
Try native splash version `flutter_native_splash 2.3.10`.

Also, there are some breaking changes in `js 0.7.0` that may not justify the update in the short term

**Comment by alexfeller** [comment]
That is what I proposed as an alternate solution. It is not about having the most recent version of the flutter_native_splash. I can use the previous one. It is more about keeping Isar up to date. The update request is not critical.

**Comment by alexfeller** [comment]
`flutter_native_splash 2.4.0` has migrated from `js` to `js_interop` Therefore there is no dependency to `js` anymore.

**Comment by AristideVB** [comment]
Hello @vicenterusso `flutter_branch_sdk` & `mobile_scanner` also need `js ^0.7.1` & many other packages, could you prioritize this update ? 🙂🙏

**Comment by vicenterusso** [comment]
> Hello @vicenterusso `flutter_branch_sdk` & `mobile_scanner` also need `js ^0.7.1` & many other packages, could you prioritize this update ? 🙂🙏

Can you provide your flutter version? or a repo? both packages installed using `js ^0.6.4`

**Comment by AristideVB** [comment]
@vicenterusso I'm using the latest flutter version `3.19.6`

`flutter_branch_sdk` `flutter_nfc_kit` are using js: ^0.7.1 as you can see here :

[flutter_branch_sdk pubspec.yaml](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/3dbada4a073f31f9012585c8f232c56057423d69/pubspec.yaml#L16)  --  [flutter_nfc_kit pubspec.yaml ](https://github.com/nfcim/flutter_nfc_kit/blob/08ce3343e8008c5631bfb79a97f3a589ae2d8894/pubspec.yaml#L19)

🙏
