### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by richard457** [isar-community/isar#37]
isar 4.0.0
```dart
 await db.variants
        .where()
        .idEqualTo(variation.id)
        .and()
        .deletedAtIsNull()
        .findFirstAsync();
```

**Comment by mrclauss** [comment]
Do you have some more details?

**Comment by mrclauss** [comment]
The problem description is unclear

**Comment by richard457** [comment]
When using async the program lags for 5 seconds vs when using non-async

**Comment by richard457** [comment]
@mrclauss I think it should not be caused because it was not addressed.

**Comment by vicenterusso** [comment]
> When using async the program lags for 5 seconds vs when using non-async

Please create a full project that reproduces this issue, not just a piece of code
