### ISSUE TITLE
Add privacy manifest for Apple

### ISSUE THREAD

**Issue by frederikstonge** [isar-community/isar#63]
https://github.com/isar/isar/issues/1601

Related to this. I was wondering if this is something that can be added to the isar-community builds for 3.x and 4.x.

**Comment by frederikstonge** [comment]
This tool can be used to generate the manifest:

https://wemakeapps.net/manifest-maker

**Comment by vicenterusso** [comment]
> This tool can be used to generate the manifest:
> 
> https://wemakeapps.net/manifest-maker

Tks for the link @frederikstonge .

Please check both PRs, tell me if you have anything to add to this issue

**Comment by frederikstonge** [comment]
Seems to be good, but I'm not sure why the build is failing.

**Comment by frederikstonge** [comment]
> The build fails for another reason.
> 
> I don't think we should have reasons for all three items. Only what Isar actually uses (even that we are no sure if Isar or limbdbx uses disk space checks)

Alright! :) It looks good then! Thank you for being so responsive!

**Comment by micodev** [comment]
* Create a new file named "PrivacyInfo.xcprivacy" in your Xcode project.
 * Add the following key-value structure to the file, replacing the placeholders with your app's specific reasons:
   <key>NSPrivacyAccessedAPITypes</key>
<array>
  <dict>
    <key>NSPrivacyAccessedAPIType</key>
    <string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
    <key>NSPrivacyAccessedAPITypeReasons</key>
    <array>
      <string>YOUR_REASON_CODE</string>
    </array>
  </dict>
  </array>

 * In Xcode, navigate to your app target and enable the "Privacy Info" capability.
 * Link the PrivacyInfo.xcprivacy file to your target. You can do this by dragging the file into the "Privacy Frameworks" section of your target's general settings.
By following these steps, you'll provide the necessary API reason descriptions without modifying the info.plist file.
 * https://stackoverflow.com/questions/78163859/itms-91053-missing-api-declaration-privacy
 *

**Comment by micodev** [comment]
* Create a new file named "PrivacyInfo.xcprivacy" in your Xcode project.
 * Add the following key-value structure to the file, replacing the placeholders with your app's specific reasons:
 ```
   <key>NSPrivacyAccessedAPITypes</key>
<array>
  <dict>
    <key>NSPrivacyAccessedAPIType</key>
    <string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
    <key>NSPrivacyAccessedAPITypeReasons</key>
    <array>
      <string>YOUR_REASON_CODE</string>
    </array>
  </dict>
  </array>
```
 * In Xcode, navigate to your app target and enable the "Privacy Info" capability.
 * Link the PrivacyInfo.xcprivacy file to your target. You can do this by dragging the file into the "Privacy Frameworks" section of your target's general settings.

https://stackoverflow.com/questions/78163859/itms-91053-missing-api-declaration-privacy

**Comment by vicenterusso** [comment]
In case you missed @micodev , we already have 2 PRs related to this issue

**Comment by frederikstonge** [comment]
Any idea when this will be merged?

**Comment by vicenterusso** [comment]
> Any idea when this will be merged?

I will suggest that @mrclauss merge this along with a new release (maybe `3.1.6+1` ?)

**Comment by frederikstonge** [comment]
> > Any idea when this will be merged?
> 
> I will suggest that @mrclauss merge #64 and #65 with a new release (maybe `3.1.6+1` ?)

And also for v4 since this is what I'm using. Also, on a side note, I have started a discussion here : 
https://github.com/isar-community/isar/discussions/67

If you could give me your input about my question, I would really appreciate. Thank you

**Comment by draskosaric** [comment]
Hi guys, any idea when a new release can be expected? Thanks in advance and thank you for keeping this project alive.

**Comment by mrclauss** [comment]
This is already contained in versions 3.1.7/4.0.3

**Comment by mrclauss** [comment]
You need to use the Isar-Community version as described in the quickstart on Isar-Community.dev

Am 9. Mai 2024 09:38:38 MESZ schrieb "Draško Sarić" ***@***.***>:
>Thanks for quick response. But, I can only see 3.1.0+1 version on
>pub.dev
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/isar-community/isar/issues/63#issuecomment-2102124503
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>

-- 
Martin Clauss
Meine Contactulater Card - All meine Kontaktinfo immer aktuell und vollständig:
https://contactulater.app/me/mc

**Comment by draskosaric** [comment]
Thanks! Again. congrats for team's hard work.
