### ISSUE TITLE
500 Internal Server when trying to import isar_flutter_libs

### ISSUE THREAD

**Issue by AhmedLSayed9** [isar-community/isar#85]
Can't import `isar_flutter_libs` to a project.
It throws the following error: `500 Internal Server Error trying to find package isar_flutter_libs at https://pub.isar-community.dev`

---

 - [x] I searched for similar issues already

**Comment by liemfs** [comment]
tha same thing happen if we run flutter pub outdated

`flutter pub outdated`
`500 Internal Server Error trying to find package isar_generator at https://pub.isar-community.dev.`
`exit code 69`

**Comment by oscarpalomar** [comment]
got the same issue

**Comment by AhmedLSayed9** [comment]
> I have almost the same error here: `503 Service Unavailable trying to find package isar_flutter_libs at https://pub.isar-community.dev.`

Yes, now i'm getting that too.
