### ISSUE TITLE
The method 'filter' isn't defined for the type 'IsarCollection'

### ISSUE THREAD

**Issue by roshanproductions** [isar-community/isar#93]
### Steps to Reproduce

- Remove the previous `isar` and `isar_flutter_libs` versions.
- Run the following command
- `flutter pub add isar:^4.0.3 isar_flutter_libs:^4.0.3 --hosted-url=https://pub.isar-community.dev`
- added named `schemas` property to isar open object
- Run `flutter pub run build_runner build`

Build runner ran successfully, but I get the following error on queries:

`The method 'filter' isn't defined for the type 'IsarCollection'`
`Try correcting the name to the name of an existing method, or defining a method named 'filter'.`

```
    final downloaderTaskCollection = _isar.downloaderTaskCollections  \\ works upto this line, but following lines produces error
        .filter()
        .mediaIdEqualTo(mediaId)
        .findFirstSync();
```
### Details

 - Dart version: [3.4.3]
 - Flutter version: [3.22.2]
 - Isar version: [4.0.3]

**Comment by vicenterusso** [comment]
can you post your collection class?

**Comment by roshanproductions** [comment]
Here you go:

```
import 'package:isar/isar.dart';

part 'downloader_task_collection.g.dart';

@collection
class DownloaderTaskCollection {

  late int id;

  String? tag;

  String? url;

  String? status;

  String? type;

  String? filename;

  double? progress;

  String? uriData;
}
```

**Comment by roshanproductions** [comment]
For some reason, helper methods are not being generated, e.g `mediaIdEqualTo()` etc..

**Comment by muhammadarifan** [comment]
Hi, is this resolved ? I also have an error like this today

**Comment by vicenterusso** [comment]
Try this:

```dart
 final downloaderTaskCollection = _isar.downloaderTaskCollections
        .where()
        .mediaIdEqualTo(mediaId)
        .findFirst();
```

* there is no `filter()` and no `findFirstSync()` in v4, because it's the default

**Comment by roshanproductions** [comment]
```
_isar. downloaderTaskCollections
        .where()
        .optional(
          taskId != null,
          (q) => q.idNotEqualTo(taskId!), // this line is not working q.idNotEqualTo
        )
```
