### ISSUE TITLE
Update android compileSdk 35 to new version

### ISSUE THREAD

**Issue by ductranit** [isar-community/isar#94]
I'm using isar 3 in my project, then I tried to upgrade compileSdk to latest api 35 and got build error from isar module.

```
Namespace not specified. Specify a namespace in the module's build file: /Users/admin/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.1.0+1/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
```
I'm not sure whether the isar v4 has updated compileSdk yet, since it isn't stable to migrate yet, so I still continue with v3.
But my project need to upgrade latest compile api, I wonder how can I bypass this build error?
### Details

 - Platform: arm Android Emulator on macos.
 - Flutter version: 3.22.3
 - Isar version:3.1.0+1

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by vicenterusso** [comment]
You are probably filling an issue in the wrong repository. This is the community version and looks like you are using `isar/isar`
