### ISSUE TITLE
Android release build fails, need to bump compileSdkVersion

### ISSUE THREAD

**Issue by Arko109** [isar-community/isar#96]
### Steps to Reproduce

1. Create empty flutter app
2. Run in release mode, it runs
3. Add isar community to pubspec as per the readme
4. Run in release mode, it fails with the following error:
```
Execution failed for task ':isar_flutter_libs:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Dev\flutter_application_1\build\isar_flutter_libs\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

### Details

 - Platform: Building in release for Android on Windows
 - Flutter version: 3.24.0
 - Isar version: 3.1.7

### Possible solution

Should be fixed if the `compileSdkVersion` in `isar_flutter_libs` is set to 31 or higher.

**Comment by Arko109** [comment]
Can confirm that the app builds when using my branch with `compileSdkVersion` 34

**Comment by pastelcode** [comment]
Hi! How did you add the package? I made dependency overrides but the app never starts, it remains in the launch screen after using your commit.

**Comment by Arko109** [comment]
I just referenced the local folder with `path:`

But maybe because I didn't actually initialize anything in the code, just added the dependency, it didn't freeze at launch

I'll take a look when I have time, if no one else does, for now I rolled back to Flutter 3.22.3

**Comment by vicenterusso** [comment]
I'm using local copy with this branch before merge #97. We should wait for @mrclauss
